phantom: 
	@echo '==> Phantom $<'
	@@cd test; ./bin/phantomjs ./run-qunit.js file://localhost/Users/toddanderson/Repositories/massroute_js/massroute-examples/common/test/index.html
	@echo

say_done:
	@echo '===> DONE!$<'
	@echo

doit: phantom say_done